name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        uses: gradle/gradle-build-action@v2.1.0
        with:
          arguments: ci
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            build/distributions/
            build/libs/
