name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build
        uses: gradle/gradle-build-action@v2.1.0
        with:
          arguments: build
      - name: Upload coverage
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.KEINCRAFT_CODACY_API }}
      - name: Upload test coverage
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.KEINCRAFT_TEST_CODACY_API }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            build/distributions/
            build/libs/
